### PR TITLE
Improved AddNode placement (+ additional fixes)

### LINKED ISSUE #758: Allow Passing Command-Line Arguments via Environment
Currently, parameters like the server password (`--password`) are passed to SEE as a command-line parameters.
This is suboptimal because passwords will show up in the operating system's process list.

The goal of this issue is to take values from environment variables.

The Gameserver container should be adapted to make use of this via its `run.sh` script.

### LINKED ISSUE #786: When a new node is added, it should not overlap with any existing sibling.
Method `AddNodeAction.AddNode` currently uses a default size for the node it creates. However, that node could overlap with any of its siblings. We need a strategy to avoid that.

### PR DESCRIPTION
**Pull request by tinxx**
This MR improves the placement of new nodes using `AddNodeAction` and provides some additional fixes.

## AddNode placement

Previously, new nodes were placed anywhere with a fixed size of `0.2`.
This led to new nodes regularly overlapping with existing nodes and several other shortcomings.

The updated logic improves various key points:
- New nodes cannot overlap with existing nodes.
  - Nodes are placed within the boundaries of their parents (similar to `MoveAction`).
  - A notification is shown if placement is not possible.
- The base size keeps the earlier relative size of `0.2` but is allowed to shrink based on the available space down to a defined minimal size.
- New nodes have a (configurable) uniform world-space height.
- The new nodes' base aspect ratio is squarified.

fixes #786

## Miscellaneous changes

- Resize handle position:
  - The resize handles are now placed on top of the resized node. This allows for a better accessibility in tightly packed constellations.
- Updated shaders:
  - The custom shaders led to a problem where resize handles were displayed over the edges or vice versa independently of the actual position of the fragments. In other words: (parts of) objects that were behind one another were printed in wrong order.
  - A two-pass shader was implemented that writes opaque edge fragments to the depth buffer while keeping `ZWrite` for semitransparent parts off. This minimizes the display artifacts with the current scenes and does not interfere with TextMeshPro's shaders while fading edges out.
- `OverlapsWithSiblings()` now ignores inactive nodes (e.g., nodes that have been deleted but are actually still hanging around invisibly).
- `BitIncrement()` and `BitDecrement()` is used to get the next greater or next smaller float value.
  - This makes it easier and more robust to set values close to a threshold while preventing instant redetection (`AddNodeAction`, `ResizeNodeAction`).
- Bump server dependency versions:
  - Frontend dependencies have been updated to (hopefully) satisfy [dependabot](https://github.com/uni-bremen-agst/SEE/security/dependabot).
  - Backend dependencies patch/incremental versions have been bumped. Some additional documentation concerning version checks and updates have been added to the README.
- Pass server configuration via environment variables (fixes #758).

----

Here there are some screenshots visualizing the shader problem:

1. Initial problem – wrong order on screen:

Screenshot From 2025-01-14 15-38-52
Screenshot From 2025-01-14 15-39-42

2. Problem using TextMeshPro's shaders in combination with `ZWrite on`:

Screenshot From 2025-01-14 15-35-43
Opaque edges for reference.

Screenshot From 2025-01-14 15-35-51
Semitransparent edges during fade-out occluding parts of the labels.

### CODE REVIEW

File: Assets/SEE/Game/SceneManipulation/SpatialMetrics.cs [hunk 1]
```diff
@@ -0,0 +1,253 @@
+﻿using System;
+using UnityEngine;
+
+namespace SEE.Game.SceneManipulation
+{
+    /// <summary>
+    /// Stores metrics that are used for working with node placement.
+    /// </summary>
+    public class SpatialMetrics
```
Comment (falko17) [inline Assets/SEE/Game/SceneManipulation/SpatialMetrics.cs:9]: This class can be made `static`.

File: Assets/SEE/Game/SceneManipulation/SpatialMetrics.cs [hunk 2]
```diff
@@ -0,0 +1,253 @@
...
+    {
+        /// <summary>
+        /// A small offset used for placement just outside specific bounds to prevent Z-fighting.
+        /// </summary>
+        public const float PlacementOffset = 0.0001f;
+
+        /// <summary>
+        /// The default local X/Z scale of a (new) node placed on another node.
+        /// </summary>
+        public static float DefaultNodeLocalScale = 0.2f;
```
Comment (falko17) [inline Assets/SEE/Game/SceneManipulation/SpatialMetrics.cs:19]: This can be const, right?

File: Assets/SEE/Game/SceneManipulation/SpatialMetrics.cs [hunk 3]
```diff
@@ -0,0 +1,253 @@
...
+        /// <summary>
+        /// Half the default local X/Z scale of a (new) node placed on another node,
+        /// typically used in bounds.
+        /// </summary>
+        public static float HalfDefaultNodeLocalScale = DefaultNodeLocalScale / 2f;
+
+        /// <summary>
+        /// The default world-space Y-axis size of a (new) node.
+        /// </summary>
+        public static float DefaultNodeHeight = 0.002f;
```
Comment (falko17) [inline Assets/SEE/Game/SceneManipulation/SpatialMetrics.cs:30]: I think these can also be `const`ants.

File: Assets/SEE/Game/SceneManipulation/SpatialMetrics.cs [hunk 4]
```diff
@@ -0,0 +1,253 @@
...
+        public float Back;
+        /// <summary>
+        /// The front side of the area.
+        /// </summary>
+        public float Front;
+
+        /// <summary>
+        /// Initializes the struct.
+        /// </summary>
+        public Bounds2D (float left, float right, float back, float front)
```
Comment (falko17) [inline Assets/SEE/Game/SceneManipulation/SpatialMetrics.cs:86]: There shouldn't be a space here:
```suggestion
        public Bounds2D(float left, float right, float back, float front)
```

File: Assets/SEE/Game/SceneManipulation/SpatialMetrics.cs [hunk 5]
```diff
@@ -0,0 +1,253 @@
...
+    /// </summary>
+    public enum Direction2D
+    {
+        Left, Right, Back, Front, None
+    }
+
+    /// <summary>
+    /// Data structure for 2-dimensional bounds.
+    /// </summary>
+    public struct Bounds2D
```
Comment (falko17) [inline Assets/SEE/Game/SceneManipulation/SpatialMetrics.cs:64]: Perhaps a `record` would be a better fit here. In that case, we'd only need to write:
```csharp
    public record Bounds2D(float Left, float Right, float Back, float Front)
```
And would automatically get those fields, a constructor taking them as parameters, a ToString method, and an Equals implementation.

File: Assets/SEE/Game/SceneManipulation/SpatialMetrics.cs [hunk 6]
```diff
@@ -0,0 +1,253 @@
...
+                        return Left;
+                    case Direction2D.Right:
+                        return Right;
+                    case Direction2D.Back:
+                        return Back;
+                    case Direction2D.Front:
+                        return Front;
+                    default:
+                        throw new IndexOutOfRangeException($"Given direction is not possible in {nameof(Bounds2D)}: {dir}");
+                }
```
Comment (falko17) [inline Assets/SEE/Game/SceneManipulation/SpatialMetrics.cs:168]: This can be a switch expression:
```suggestion
                return dir switch
                {
                    Direction2D.Left => Left,
                    Direction2D.Right => Right,
                    Direction2D.Back => Back,
                    Direction2D.Front => Front,
                    _ => throw new IndexOutOfRangeException($"Given direction is not possible in {nameof(Bounds2D)}: {dir}")
                };
```

File: Assets/SEE/Game/SceneManipulation/SpatialMetrics.cs [hunk 7]
```diff
@@ -0,0 +1,253 @@
...
+        /// <summary>
+        public static implicit operator string(Bounds2D bounds)
+        {
+            return bounds.ToString();
+        }
+
+        /// <summary>
+        /// Returns a printable string with the struct's values.
+        /// <summary>
+        public override readonly string ToString()
```
Comment (falko17) [inline Assets/SEE/Game/SceneManipulation/SpatialMetrics.cs:203]: Order should be `readonly override`:
```suggestion
        public readonly override string ToString()
```

File: Assets/SEE/Game/SceneManipulation/SpatialMetrics.cs [hunk 8]
```diff
@@ -0,0 +1,253 @@
...
+        /// <param name="other">The bounds of another object.</param>
+        /// <returns><c>true</c> iff the bounds overlap.</returns>
+        public bool HasOverlap(Bounds2D other)
+        {
+            if (Front < other.Back || Back > other.Front || Left > other.Right || Right < other.Left)
+            {
+                // No overlap detected
+                return false;
+            }
+            return true;
```
Comment (falko17) [inline Assets/SEE/Game/SceneManipulation/SpatialMetrics.cs:220]: Can be rewritten as:
```suggestion
            return Front >= other.Back && Back <= other.Front && Left <= other.Right && Right >= other.Left;
```

File: Assets/SEE/GameObjects/GameObjectExtensions.cs [hunk 9]
```diff
@@ -1033,18 +1060,18 @@ public static GraphElementOperator Operator(this GameObject gameObject)
         }
 
         /// <summary>
-        /// Checks if <paramref name="gameObject"/> overlaps with any other direct child node of its parent.
+        /// Checks if <paramref name="gameObject"/> overlaps with any other acrtive direct child node of its parent.
```
Comment (falko17) [inline Assets/SEE/GameObjects/GameObjectExtensions.cs:1063]:
```suggestion
        /// Checks if <paramref name="gameObject"/> overlaps with any other active direct child node of its parent.
```

File: Assets/SEE/Utils/SEEMath.cs [hunk 10]
```diff
@@ -0,0 +1,111 @@
...
+    /// <summary>
+    /// This class contains additional mathematical functions.
+    /// <para>
+    /// Individual methods may be copied from other sources like newer versions of dotnet framework.
+    /// Please consult method descriptions for credits and license.
+    /// </para>
+    /// </summary>
+    public static partial class SEEMath
+    {
+
```
Comment (falko17) [inline Assets/SEE/Utils/SEEMath.cs:14]:
```suggestion
```

File: Assets/SEE/Utils/SEEMath.cs [hunk 11]
```diff
@@ -0,0 +1,111 @@
...
+namespace SEE.Utils
+{
+    /// <summary>
+    /// This class contains additional mathematical functions.
+    /// <para>
+    /// Individual methods may be copied from other sources like newer versions of dotnet framework.
+    /// Please consult method descriptions for credits and license.
+    /// </para>
+    /// </summary>
+    public static partial class SEEMath
```
Comment (falko17) [inline Assets/SEE/Utils/SEEMath.cs:12]: Why is this class `partial`?

File: Server/Backend/README.md [hunk 12]
```diff
@@ -39,6 +39,50 @@ Metadata to identify and retrieve files are stored in the relational database, w
...
+You can use the following command to check for outdated versions of direct dependencies:
+
+```sh
+./mvnw versions:display-dependency-updates
+```
+
+Please note that updating dependencies might require code changes.
+It is usually safe -- and strongly suggested -- to bump patch level versions.
+This is typically the third part of the version number, e.g., `1.2.3` -> `1.2.5`.
+Changes to the first two segments are often associated to breaking changes and need additional manual review and testing.
```
Comment (falko17) [inline Server/Backend/README.md:56]: This should only be true for the first segment, right? Or are the dependencies using something other than semantic versioning?

**Review by falko17 — CHANGES_REQUESTED** [review]
Thank you for the PR! I only have minor comments, which are listed below.

File: Assets/SEE/Controls/Actions/AddNodeAction.cs [hunk 13]
```diff
@@ -44,16 +45,22 @@ private enum ProgressState
...
-        private Vector3 position;
+        private Vector3 contextMenuTargetLocalPosition;
+
+        /// <summary>
+        /// Tolerance value for comparing localScale to minimal size threshold.
+        /// <para>
+        /// This is necessary to compensate for precision fluctuations in float values.
+        /// </para>
+        /// </summary>
+        private const float tolerance = 0.0001f;
```
[the remark this answers is not in the document]
Comment (tinxx) [reply Assets/SEE/Controls/Actions/AddNodeAction.cs:63]: The tolerance is finely tuned so that node creation works as expected.

File: Assets/SEE/Controls/Actions/AddNodeAction.cs [hunk 14]
```diff
@@ -104,30 +108,338 @@ public override bool Update()
...
+                bounds.Front = parentBounds.Front;
+                bounds.Back = Mathf.Max(bounds.Back - diff, parentBounds.Back);
+            }
+
+            // Shrink by raycasting on X/Z axes
+            List<Bounds2D> siblingBoundsList = new();
+            Bounds2D potentialGrow = new(0f, 0f, 0f, 0f);
+            foreach (Transform sibling in parent.transform)
+            {
+                if (!sibling.gameObject.IsNodeAndActiveSelf())
```
[the remark this answers is not in the document]
Comment (tinxx) [reply Assets/SEE/Controls/Actions/AddNodeAction.cs:164]: I have previously structured the code with comments, but I will use method-local functions instead now. Using methods would result in an overhead due to shared variables.

File: Assets/SEE/Controls/Actions/AddNodeAction.cs [hunk 15]
```diff
@@ -104,30 +108,338 @@ public override bool Update()
...
+            {
+                if(!bounds.HasOverlap(siblingBounds))
+                {
+                    continue;
+                }
+
+
+                // Determine shrink direction: weight by area size
+                float area = 0f;
+                float potentialArea;
```
[the remark this answers is not in the document]
Comment (tinxx) [reply Assets/SEE/Controls/Actions/AddNodeAction.cs:219]: The result of the previous blocks is used in the successive ones.

File: Assets/SEE/Controls/Actions/AddNodeAction.cs [hunk 16]
```diff
@@ -104,30 +108,338 @@ public override bool Update()
...
+                            continue;
+                        }
+                        oldValue = bounds.Front;
+                        bounds.Front = Mathf.Min(bounds.Front + potentialGrow.Front, parentBounds.Front);
+                        break;
+                    default:
+                        continue;
+                }
+
+                float newValue;
```
[the remark this answers is not in the document]
Comment (tinxx) [reply Assets/SEE/Controls/Actions/AddNodeAction.cs:338]: That was meant as a performance optimization. But we can probably leave that to the compiler.

File: Assets/SEE/Controls/Actions/AddNodeAction.cs [hunk 17]
```diff
@@ -104,30 +108,338 @@ public override bool Update()
...
+                    if (direction == Direction2D.Back && bounds.Back < siblingBounds.Front &&
+                            (newValue = SEEMath.BitIncrement(siblingBounds.Front)) <= oldValue)
+                    {
+                        bounds.Back = newValue;
+                    }
+                    if (direction == Direction2D.Front && bounds.Front > siblingBounds.Back &&
+                            (newValue = SEEMath.BitDecrement(siblingBounds.Back)) >= oldValue)
+                    {
+                        bounds.Front = newValue;
+                    }
```
[the remark this answers is not in the document]
Comment (tinxx) [reply Assets/SEE/Controls/Actions/AddNodeAction.cs:365]: Your suggestion actually changes the logic as it is no if/else-if construct. I leave it as-is.

File: Assets/SEE/Controls/Actions/ResizeNodeAction.cs [hunk 18]
```diff
@@ -603,15 +587,40 @@ void UpdateSize()
...
+                    float deltaX = (currentResizeStep.InitialMousePosition.x - Input.mousePosition.x) * currentResizeStep.InvScreenHeight;
+                    float deltaY = (currentResizeStep.InitialMousePosition.y - Input.mousePosition.y) * currentResizeStep.InvScreenHeight;
+
+                    cursorMovement = new Vector3(
+                            (cameraPlanarRight.x * deltaX + cameraPlanarForward.x * deltaY) * currentResizeStep.Direction.x,
+                            0f,
+                            (cameraPlanarRight.z * deltaX + cameraPlanarForward.z * deltaY) * currentResizeStep.Direction.z);
                 }
                 Vector3 newLocalSize = currentResizeStep.InitialLocalSize - Vector3.Scale(currentResizeStep.LocalScaleFactor, cursorMovement);
                 Vector3 newLocalPosition = currentResizeStep.InitialLocalPosition
```
[the remark this answers is not in the document]
Comment (tinxx) [reply Assets/SEE/Controls/Actions/ResizeNodeAction.cs:626]: Linq magic :)

File: Assets/SEE/Game/SceneManipulation/SpatialMetrics.cs (hunk 5 above)
Comment (tinxx) [reply Assets/SEE/Game/SceneManipulation/SpatialMetrics.cs:64]: A record struct has init-only attributes. The current implementation allows the fields to be changed after init.

File: Assets/SEE/Utils/SEEMath.cs (hunk 11 above)
Comment (tinxx) [reply Assets/SEE/Utils/SEEMath.cs:12]: I initially intended only to include content with the same license and origin in the file and create a different one for our own code.

File: Server/Backend/README.md (hunk 12 above)
Comment (tinxx) [reply Server/Backend/README.md:56]: We cannot guarantee that dependencies use semantic versioning.

**Comment by tinxx** [comment]
Thanks for the review @falko17!

I have incorporated most of the suggested changes.

File: Assets/SEE/Controls/Actions/AddNodeAction.cs (hunk 15 above)
[the remark this answers is not in the document]
Comment (falko17) [reply Assets/SEE/Controls/Actions/AddNodeAction.cs]: Is it really? Isn't it re-defined before each use?

image

File: Assets/SEE/Controls/Actions/AddNodeAction.cs (hunk 17 above)
[the remark this answers is not in the document]
Comment (falko17) [reply Assets/SEE/Controls/Actions/AddNodeAction.cs]: Keeping this resolved since it's just a style choice, but does it really change the logic? Unless I'm misreading this, it seems like the `direction` check at the start of each condition does effectively turn this into an if/else-if construct.

File: Assets/SEE/Controls/Actions/AddNodeAction.cs (hunk 15 above)
[the remark this answers is not in the document]
Comment (tinxx) [reply Assets/SEE/Controls/Actions/AddNodeAction.cs]: You are right, it was merely a performance optimization. The variable is reused.

File: Assets/SEE/Controls/Actions/AddNodeAction.cs [hunk 19]
```diff
@@ -104,30 +108,338 @@ public override bool Update()
...
+                float targetMovement = targetPosition.z - position.z;
+                float actualMovement = Mathf.Min(maxMovement, Mathf.Abs(targetMovement));
+                if (targetMovement >= 0f)
+                {
+                    position.z += actualMovement;
+                }
+                else
+                {
+                    position.z -= actualMovement;
+                }
```
[the remark this answers is not in the document]
Comment (falko17) [reply Assets/SEE/Controls/Actions/AddNodeAction.cs]: I'm going to defer to your judgment here, so we can keep it as-is.

**Review by falko17 — APPROVED** [review]
Only four remaining small comments, so I'll approve already.

File: Assets/SEE/Controls/Actions/AddNodeAction.cs [hunk 20]
```diff
@@ -130,312 +131,332 @@ private void AddNode(GameObject parent, Vector3 targetPosition)
...
-                bounds.Front = Mathf.Min(bounds.Front + diff, parentBounds.Front);
-            }
-            if (bounds.Front > parentBounds.Front)
+            List<Bounds2D> siblingBoundsList = new();
+            Bounds2D potentialGrow = new(0f, 0f, 0f, 0f);
+
+            moveInsideParentArea();
+            shrink2D();
+            preventOverlap();
+            fillAvailableSpace();
```
[the remark this answers is not in the document]
Comment (tinxx) [reply Assets/SEE/Controls/Actions/AddNodeAction.cs]: Applying PascalCase :)

[the remark this answers is not in the document]
Comment (koschke) [reply Assets/SEE/Controls/Actions/AddNodeAction.cs]: Yes, PascalCase it should be.
